### ISSUE TITLE
Not listening a docker-in-docker container exposed port into a container

### ISSUE THREAD

**Issue by tdesvenain** [jpetazzo/dind#94]
Hi, i have a jenkins container linked with dind

```
jenkins:
    image: contentsquare/cs-jenkins:latest
    links:
    - dind
    volumes:
    - ./jenkins/.dockercfg:/root/.dockercfg
    - ./jenkins/data:/var/jenkins_home
    extra_hosts:
    - ci-hub.content-square.fr:0.0.0.0
    - ci-uxanalytics.content-square.fr:0.0.0.0

dind:
    build: jenkins/dind
    expose:
    - 4242
    environment:
      PORT: 4242
    privileged: true
    volumes:
    - ./jenkins/data:/var/jenkins_home
```

within the jenkins container, i run a composition of containers

```
nginx:
    image: nginx
    links:
    - php:webstack_php
    - php55:webstack_php55
    volumes:
    - ./nginx.conf:/nginx.conf
    ports:
    - 80:80
    command: nginx -c /nginx.conf
    volumes_from:
    - php55


php55:
    image: my/php55
    links:
    - redis:webstack_redis
    [...]
```

i can run commands on nginx, php55, etc containers but when i run composition with docker-compose up, it is not listening on port 80 from jenkins container

is there a way to listen a service provided by a docker in docker from the docker container where we launched it ?
